name: Build, test, deploy recipe

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    uses: shredeagle/reusable-workflows/.github/workflows/main_build.yml@v2.5.0
    with:
      os: >-
        ["ubuntu-22.04", "windows-2022"]
      deployrecipe_userchannel: adnn/develop
    secrets:
      SHREDROBOT_GITHUB_TOKEN: ${{ secrets.SHREDROBOT_GITHUB_TOKEN }}
      ACTION_CACHENAME: ${{ secrets.ACTION_CACHENAME }}
      CONAN_USER_NAME: ${{ secrets.CONAN_USER_NAME }}
      CONAN_USER_PASSWORD: ${{ secrets.CONAN_USER_PASSWORD }}
