name: Build, test, deploy recipe

on:
  push:
    tags:
      - v*.*.*

jobs:
  extract_tag:
    uses: shredeagle/reusable-workflows/.github/workflows/extract_version_tag.yml@v2.5.0

  build:
    needs: extract_tag
    uses: shredeagle/reusable-workflows/.github/workflows/main_build.yml@v2.5.0
    with:
      os: >-
        ["ubuntu-22.04", "windows-2022"]
      deployrecipe_userchannel: adnn/stable
      version: ${{ needs.extract_tag.outputs.version }}
    secrets:
      SHREDROBOT_GITHUB_TOKEN: ${{ secrets.SHREDROBOT_GITHUB_TOKEN }}
      ACTION_CACHENAME: ${{ secrets.ACTION_CACHENAME }}
      CONAN_USER_NAME: ${{ secrets.CONAN_USER_NAME }}
      CONAN_USER_PASSWORD: ${{ secrets.CONAN_USER_PASSWORD }}
